### PR TITLE
Initial draft of a checkoff penalizer. 

### PR DESCRIPTION
**Pull request by dbecker1**
Goal is to cross reference the submission name with the list of students who have been checked off for attendance. This way, when a student is checked off during a Timed Lab, any submission after that will automatically give them a 0. 

I've never really used python, so any stylistic comments would be greatly appreciated.

### CODE REVIEW

**Comment by dbecker1** [comment]
> I believe we can easily fix the hack in the gradescope.py file, it shouldn’t be merged in this form. Will look tomorrow.

Not planning on merging this quite yes. Just wanted to get it up here

**Comment by dbecker1** [comment]
I agree about the security of it. Another potential option would be to modify the attendance system to generate another sheet that only has the hashed GTIDs. Then, we can get the GTID from the metadata, hash it, and compare to that list. That way the only exposed information is a useless list of strings. 

On a related note, I wonder if attendance for Timed Labs is actually FERPA protected... Especially considering the fact that its not directly applied to their grades.

**Comment by dbecker1** [comment]
Also flakes is the most annoying thing ever

**Comment by skyman** [comment]
Unfortunately with gtIDs being numeric and with any salting method being visible to the student from the source in the container, once they have access to the hashed data it’s trivial to brute force by hashing all possible gtIDs to find original gtIDs matching the hashed entries, although that is a rather complicated attack nobody will bother with.

Nonetheless what I’m trying to point out is that we need a solution that does not expose all data to the containerized, student-modifiable code. (i.e. somehow, every student should be able to access their own data only.) Attendance data clearly isnt so critical since we have it on Drive in the first place, but I think this is something to consider as we place more trust on these containers. I can’t think of anything right now that does not involve running and external app or a more complicated submission procedure, but let’s think about it.

**Comment by dbecker1** [comment]
That’s fair. At the end of the day, it comes down to how crucial is this data and is protecting it at all costs really worth the effort. If you think about it, a student would only have the ability to submit to this image for a time period of at most 5 hours. I would be incredibly impressed if someone pulled that off in that much time, and even if they did, they really didn’t gain much valuable information. I’m just not sure if it’s worth going through the effort of devising a system to completely isolate the container from the data.

**Comment by dbecker1** [comment]
I’ve also previously been told by the registrar that we are allowed to keep hashes of ids in an unsecured system. We just have to give it our best effort to protect them, but it’s not like we are dealing with SSNs

**Comment by skyman** [comment]
So the issue with the metadata I think is not an issue - what happens there is users is an array because Gradescope allows group submissions and I think it would be nice if zucchini doesn't break support for that feature with this version.

So what I think we should do is make zucchini support multiuser submissions too instead. I'll take a better look into this later today when I'm back home, but the change is trivial except for where it involves the Canvas code from our legacy workflow. I'll branch off of this PR branch and PR into it when done, shouldn't take too long.

If I somehow am unable to do that today, I will still approve the PR so that we can merge this in its current state and I'll add the multiuser patch later.

**Comment by dbecker1** [comment]
For the sake of tracking what's going on:

I refactored the Checkoff Penalizer to hit an API instead of accessing Google Sheets directly. The config now takes in an API url and an API key. The API should take a post request containing the student_name and attendance_event and return true or false based on whether or not the student was in attendance. No student information is available to the container now. In addition, this allows us to abstract away google sheets so that it could theoretically be used with any attendance system.

**Comment by skyman** [comment]
So I looked at this and from what I understand the hack wasn't necessary in the first place? I went ahead and removed it and added the key back to the attrs list.

Obviously I can't test this though, so it would be great if you can do that @dbecker1

**Comment by dbecker1** [comment]
That worked! Thanks for looking at it. I'll merge it in now

**Pull request merged**
