### PR TITLE
Gradescope bridge

### PR DESCRIPTION
**Pull request by ausbin**
Support generating a gradescope autograder .zip.

You can do something like

```
$ make dist
$ cd path/to/assignment/
$ zucc gradescope zip --wheel /path/to/zucchini/repo/dist/*.whl
```

or to use the version of zucchini in pip

```
zucc gradescope zip
```

### CODE REVIEW

**Comment by ausbin** [comment]
1. I'm not sure how to do this honestly. I've been researching for like 20 minutes and I'm not sure how to find the path of a .whl for a given package. We could use the current version tho, is that better? Much more doable imo
2. Yea it looks gross i agree. Those are floats tho so I'm not sure how to fix. 2 decimal places might not be representable finitely in floating point, and some fixed number of binary decimals may not be representable in a finite number of base 10 decimal points. I can try passing a string tonight, any other ideas tho?

**Comment by skyman** [comment]
For 1, instead of finding the wheel, one option is to use the python `wheel` module to _build_ the wheel from scratch instead of using a prebuilt one, but let's save that for later I guess since it might be a bit complicated.

For 2, the two things I can think of are:
- We use the weights as the max scores (it will be an integer, however, the scores will not add to 100).
- We decide how many decimal places we want (lets say 2) and we make the total score out of `100 * 10^numdecimalplaces` (so in this case the score is out of 10000 and all scores are proper integers, students can just divide by 100 in their head)

Neither option is too good, but then again, we can't accurately pass decimal numbers with json unless the gradescope dudes support decimal parsing from strings which I doubt is true :(

**Comment by skyman** [comment]
I'm really surprised that gradescope accepts strings for the score actually, but yeah this is awesome.

One minor concern is how our rounding does not ensure that the scores add up to 100. For example, if you have 3 components of weight 1, the highest score you can get is 99.99 - and this becomes worse for example if you have 300 components and now the highest score is 99. We should make sure that the scores add up to 100 even if it means making the last one weigh more than the others. Could you add that as well?

Also, I'll add to our todo list an item to query the PyPI api to check if the current zucchini version exists on there (and the command will fail otherwise).

**Comment by ausbin** [comment]
> One minor concern is how our rounding does not ensure that the scores add up to 100. For example, if you have 3 components of weight 1, the highest score you can get is 99.99 - and this becomes worse for example if you have 300 components and now the highest score is 99. We should make sure that the scores add up to 100 even if it means making the last one weigh more than the others. Could you add that as well?

we send the calculated score total score fwiw, so this would only be a problem afaict if some student is really really really bored. is that bad? i was viewing them as an approximation

**Comment by skyman** [comment]
Oh, so we're calculating the total score as a fraction first and converting it to decimal separately, and we're using it on the total score field to override gradescope from adding the scores together by itself? That's really smart actually, sorry for not noticing that haha

**Pull request merged**
